### ISSUE TITLE
Setting Arch as default OS

### ISSUE THREAD

**Issue by 0xdhrv** [xeffyr/alpine-term#10]
This is definitely not an issue, but I want to set Arch Linux as the default OS that boots up rather than Alpine Linux. Further, I don't have any storage issues, however, is it possible to completely remove the other files which are not necessary for booting the Arch Linux.

PS . : this whole concept is so so amazing, I already like the idea of this app : ) Good Work!

**Comment by xeffyr** [comment]
No, this is not possible. The default boot device is the first drive specified on QEMU command line, so that configuration is hardcoded. Even if application will swap disks and make secondary one as default boot device, that will break application if secondary disk is not bootable. QEMU just doesn't support fallback to next disk of same type and will boot CD instead.

If you really need to boot only from Arch Linux, I suggest to replace the Alpine Linux with it. There is a "hack" with `drive_backup` command which will repace the original image with yours: https://xeffyr.github.io/alpine-term/docs/help.html#restoring-the-hdd-image.
