### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by ElytrA8** [xeffyr/alpine-term#19]
Is there any support for Desktop Environments

**Comment by xeffyr** [comment]
Within app - no. I will not embed any VNC/Xorg viewer within app, "ultimate" build variant however has noVNC VNC client which is web-based. You'll need to run nginx & do port forwarding to use it.

Otherwise, use VNC Viewer by RealVNC from Google Play.

How to do graphics in Alpine Linux, check https://wiki.alpinelinux.org/wiki/Tutorials_and_Howtos#Desktop_Environment.

**Comment by xeffyr** [comment]
https://github.com/xeffyr/alpine-term/issues/18#issuecomment-666394120
