### ISSUE TITLE
Increase Ram/Core

### ISSUE THREAD

**Issue by alexandrebfaust** [xeffyr/alpine-term#23]
Hey! I'm coming here, cause I already searched ALL the internet for this information, and unfortunately I didn't find it.
How I can increase ram/core using the Alpine Term? Currently using only 1 core and 2GB ram.

![Alpine Term Infos](https://i.imgur.com/o4h1W3H.jpg)

**Comment by WMCB-Tech** [comment]
That's the same thing that I ask. but unfortunately. Alpine Term only sticks to one configuration and it's hardcoded. to keep the app stable to prevent crashing

If you need customization. use Termux. with `qemu-system-x86_64` headless

**Comment by xeffyr** [comment]
Alpine Term automatically sets the RAM size. The max possible safe choice is about 50-55% of host RAM. With more allocated RAM, chances that app will be killed by Android drastically increase.

Number of emulated CPU cores is set to `1` due to number of issues:
* All CPU cores are emulated within single thread in round-robin fashion. As result, having multiple of them will cause certain hit on single-process performance.
* MTTCG is not supported. It is possible to have it when emulating x86_64 on x86_64, but not when x86_64 on aarch64 or arm as there it is very unstable (boot issues). MTTCG also increases device heating and battery usage.

**Comment by xeffyr** [comment]
I'm going to release a v12.0 soon which will contain few changes regaring CPU cores and RAM:
* CPU will have 4 cores but only 1 will be active after boot by default (controlled through kernel command line).
* RAM will support hot plugging up to 16 GB (controlled through monitor console).

Statement in https://github.com/xeffyr/alpine-term/issues/23#issuecomment-685978731 still be valid.
