### ISSUE TITLE
Add Virtio Balloon Device Feature

### ISSUE THREAD

**Issue by WMCB-Tech** [xeffyr/alpine-term#29]
Hey @xeffyr I was just wondering if you can add VirtIO Balloon Device to Alpine Term. as far as I know. Virtio Balloon can free up Unallocated RAM memory in the guest os and claiming it to the host. just like closing other applications to free up memory

I don't know if Alpine Linux or alpine term Supports memory ballooning. but I think most kernels Support this.

But I think this is useful feature if I stop services and keep the app running without closing it. so to prevent the system to killing the application

**Comment by xeffyr** [comment]
Ok, will look on it.

**Comment by xeffyr** [comment]
This feature is going to be added in next release. Even such small change to emulated hardware as enabling balloon device invalidates snapshots, `loadvm` won't work on snapshots made in previous version. Have to make it "major" v13.0 instead of v12.2 due to incompatible changes. As bonus, will update hdd images.

Now the note on "ballooning" feature: *it doesn't de-allocate used memory automatically*. As stated in https://www.linux-kvm.org/page/Projects/auto-ballooning, auto-ballooning is experimental project which is not finished.

As workaround, you will need to use monitor command, e.g.
```
balloon 300
balloon 1024
```
to reset memory allocation.

**Comment by WMCB-Tech** [comment]
I tried to reset memory allocation to 300 but it gives me an error
`Error: No balloon device has been activated`

I think Virtio Balloon needs to be activated by adding this argument (Not in Monitor):
`-device virtio-balloon`

**Comment by xeffyr** [comment]
> I tried to reset memory allocation to 300 but it gives me an error

Because current version doesn't have support for balloon device. Only v13.x and higher will have it.

> I think Virtio Balloon needs to be activated by adding this argument inside this script (Not in Monitor)

This script is not used by Alpine Term.

Added in https://github.com/xeffyr/alpine-term/commit/fd5bb0dd8d9db711fd73e396de7f30669d37a6aa

**Comment by WMCB-Tech** [comment]
Oh. Ok thanks. I thought the walkaround will work.

**Comment by xeffyr** [comment]
That workaround is actually manual memory management with commands like `balloon 500`. Automatic "ballooning" doesn't work as not implemented in QEMU.

In a real-world use this is handled by libvirt.

**Comment by xeffyr** [comment]
v13.0 is now available.

**Comment by WMCB-Tech** [comment]
Thanks. Keep up the good work
