### ISSUE TITLE
Resize root partition

### ISSUE THREAD

**Issue by WMCB-Tech** [xeffyr/alpine-term#30]
Hey. sorry for the disturbance but how can i resize root partition using `fdisk` and `resize2fs` in alpine term. i tried to resize the partition using cfdisk but the changes cannot be saved when hitting quit, i think previous versions of alpine term has a transcript how to resize it but now. i can't find it. i googled about how to resize root partition in linux but i might break something.

Can you give me the commands or is there an easier way to resize the root partition

**Comment by xeffyr** [comment]
The way tobresize disk partition is **exactly same** as for typical Linux distribution. There lots of information on the Internet how to use fdisk and resize2fs. Due to that, Alpine Term now don't provide such information on help page anymore.

https://askubuntu.com/questions/24027/how-can-i-resize-an-ext-root-partition-at-runtime
