### ISSUE TITLE
Request: qemu-guest-agent by default

### ISSUE THREAD

**Issue by lars18th** [xeffyr/alpine-term#5]
Hi,

https://pve.proxmox.com/wiki/Qemu-guest-agent
Even we can install it with `apk -U add qemu-guest-agent`, why not include it installed by default?

Regards.

**Comment by xeffyr** [comment]
Each enabled service consumes CPU cycles which are very expensive in emulator (that's why I chose Alpine Linux and not something else). If you really need guest agent, install it.

Changes to default HDD image require releasing a new major version + app data cleanup after update. Guest agent also requires to be exposed somehow to host, but I'm not going to implement additional communication interfaces beyond existing ones.

What you expect from `qemu-guest-agent` ?
